images:
  aptos-ubuntu-x64:
    platform: "linux"
    arch: "x64"
    ami: "ami-05f29bbd9fcfcca20"
  aptos-ubuntu-x64-latest:
    platform: "linux"
    arch: "x64"
    owner: "058264343338" # aptos-ci AWS account id
    name: "aptos-runs-on-*"
